// Path allowlist + safe-filename helpers for the Birthday Image Studio.
// Every path that touches disk MUST go through one of these helpers so that
// path traversal (../, absolute paths, symlink escapes, etc.) is rejected.
'use strict';

const path = require('path');

// Tiles-photo allowlist logic is shared with the permanent Rida Studio game
// (lib/shared/tilesPhotos.js) so both validate reference photos identically.
const tilesPhotos = require('../../lib/shared/tilesPhotos');

const REPO_ROOT = tilesPhotos.REPO_ROOT;
const TILES_PHOTOS_DIR = tilesPhotos.TILES_PHOTOS_DIR;
const TILES_MANIFEST_PATH = tilesPhotos.TILES_MANIFEST_PATH;
const CANDIDATES_ROOT = path.join(REPO_ROOT, '.birthday-studio', 'candidates');
const GENERATED_ROOT = path.join(REPO_ROOT, 'public', 'birthday', 'generated');
const GENERATED_MANIFEST_PATH = path.join(GENERATED_ROOT, 'manifest.json');
// Local-only owner identity pack for the Rida Studio production game — see
// tools/BIRTHDAY-IMAGE-STUDIO.md. Gitignored; never committed.
const RIDA_IDENTITY_PATH = path.join(REPO_ROOT, '.birthday-studio', 'rida-identity.json');

// Only plain "photo-<digits>.jpg" style names are ever accepted as reference
// photos — this matches the existing tiles manifest.json contents exactly.
const SAFE_PHOTO_NAME = tilesPhotos.SAFE_PHOTO_NAME;
// job ids and candidate file names are generated by us (see store.js) but we
// still validate anything coming back from the client before touching disk.
const SAFE_JOB_ID = /^job-[0-9]{13,20}-[a-f0-9]{8}$/;
const SAFE_CANDIDATE_FILE = /^candidate-[1-4]\.png$/;

/**
 * Resolve `name` as a photo file inside public/tiles/photos, verifying it is
 * both a syntactically safe name AND listed in the tiles manifest.json, AND
 * that the resolved absolute path stays inside TILES_PHOTOS_DIR.
 * Throws on any violation — callers should catch and return a JSON error.
 */
function resolveAllowedPhoto(name, manifestNames) {
  return tilesPhotos.resolveAllowedPhoto(name, manifestNames);
}

/** Validate a job id produced by store.js before using it in a path. */
function assertSafeJobId(jobId) {
  if (typeof jobId !== 'string' || !SAFE_JOB_ID.test(jobId)) {
    throw new Error(`Invalid job id: ${JSON.stringify(jobId)}`);
  }
  return jobId;
}

/** Validate a candidate file name (e.g. "candidate-1.png") before use. */
function assertSafeCandidateFile(fileName) {
  if (typeof fileName !== 'string' || !SAFE_CANDIDATE_FILE.test(fileName)) {
    throw new Error(`Invalid candidate file name: ${JSON.stringify(fileName)}`);
  }
  return fileName;
}

/** Resolve a candidate's absolute path, guaranteeing it stays under the job folder. */
function resolveCandidatePath(jobId, fileName) {
  assertSafeJobId(jobId);
  assertSafeCandidateFile(fileName);
  const jobDir = path.resolve(CANDIDATES_ROOT, jobId);
  if (path.dirname(jobDir) !== CANDIDATES_ROOT) {
    throw new Error(`Job path escapes candidates root: ${jobId}`);
  }
  const filePath = path.resolve(jobDir, fileName);
  if (path.dirname(filePath) !== jobDir) {
    throw new Error(`Candidate path escapes job directory: ${fileName}`);
  }
  return { jobDir, filePath };
}

/**
 * Build a safe, collision-free filename for an approved export under
 * public/birthday/generated/. Strips everything except a small charset and
 * appends a short random suffix so repeated approvals never collide.
 */
function safeExportFilename(baseHint, extension) {
  const cleanedHint = String(baseHint || 'birthday-photo')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'birthday-photo';
  const suffix = require('crypto').randomBytes(4).toString('hex');
  const ext = extension.replace(/^\./, '');
  return `${cleanedHint}-${suffix}.${ext}`;
}

/** Ensure the resolved absolute path for a generated export stays inside GENERATED_ROOT. */
function resolveGeneratedPath(fileName) {
  if (typeof fileName !== 'string' || !/^[a-z0-9-]{1,80}\.(png|jpg|jpeg|webp)$/i.test(fileName)) {
    throw new Error(`Invalid generated file name: ${JSON.stringify(fileName)}`);
  }
  const filePath = path.resolve(GENERATED_ROOT, fileName);
  if (path.dirname(filePath) !== GENERATED_ROOT) {
    throw new Error(`Generated path escapes allowed directory: ${fileName}`);
  }
  return filePath;
}

function readTilesManifest() {
  return tilesPhotos.readTilesManifest();
}

module.exports = {
  REPO_ROOT,
  TILES_PHOTOS_DIR,
  TILES_MANIFEST_PATH,
  CANDIDATES_ROOT,
  GENERATED_ROOT,
  GENERATED_MANIFEST_PATH,
  RIDA_IDENTITY_PATH,
  SAFE_PHOTO_NAME,
  SAFE_JOB_ID,
  SAFE_CANDIDATE_FILE,
  resolveAllowedPhoto,
  assertSafeJobId,
  assertSafeCandidateFile,
  resolveCandidatePath,
  safeExportFilename,
  resolveGeneratedPath,
  readTilesManifest,
};
